### PR TITLE
Add Async Iterator Support to Query Subscription

### PR DESCRIPTION
**Pull request by Toubat**
Allows developer to async iterate on query subscription:
```py
client = ConvexClient('https://example-xxx-xxx.convex.cloud')

qs = client.subscribe("messages:latestMessage")
async for part in qs:
    print(part)
```

----

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by Toubat** [comment]
Hi @thomasballinger! Just checking in to see if there’s any update on the status of this PR. Thanks!

**Comment by thomasballinger** [comment]
Hey @Toubat, sorry for the delay here! No concerns here, @anjanbharadwaj even wrote something like this when he was implementing this and I pulled it just to start the API off smaller.

Since this is pretty stable but we're still in 0.6.0, no concerns, let's see how it goes.

**Review by thomasballinger — APPROVED** [review]

**Comment by thomasballinger** [comment]
@Toubat I'll we'll get a release out by next week!

**Comment by thomasballinger** [comment]
@Toubat this is in https://github.com/get-convex/convex-py/commit/76fb9aab7970c7dae5a0021d12826153ac2b71e3, will close when we get a release out.

**Pull request closed without merging**
